### ISSUE TITLE
Riot Games API v3: Update all endpoints to support new format.

### ISSUE THREAD

**Issue by taycaldwell** [taycaldwell/riot-api-java#89] opened 2017-04-05 03:11 UTC
The format of all API endpoints are being standardized to adhere to following format:
```
https://{platform}.api.riotgames.com/{game}/{service}/{version}/{resource}
```

As these changes are rolled out, all endpoints should be updated to follow this new format.

**Acceptance Criteria:**
All API endpoints now follow the new format as described above.

**Comment by taycaldwell** [comment] 2017-04-05 03:17
This story is potentially blocked, or should be worked in conjunction with https://github.com/taycaldwell/riot-api-java/issues/90

**Comment by Linnun** [comment] 2017-04-05 19:00
I would actually call this a duplicate of #90. Riot is updating all their APIs to work with this format in v3. By converting our methods to the new APIs as they get available, we automatically follow the new format.

**Closed** 2017-06-11 15:45 UTC
Labels: enhancement
